# Generated by Django 2.2.8 on 2020-12-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201222_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='dddddd', upload_to='posts'),
        ),
    ]
